import AsyncStorage from '@react-native-async-storage/async-storage';
import React, { createContext, useContext, useEffect, useState } from 'react';

export type Idioma = 'es' | 'en';

export const textos = {
  es: {
    appNombre: '🎁 Giftu',
    iniciaSesion: 'Inicia sesión',
    correo: 'Correo electrónico',
    contrasena: 'Contraseña',
    entrar: 'Entrar',
    noTieneCuenta: '¿No tienes cuenta? Regístrate',
    errorCredenciales: 'Email o contraseña incorrectos',
    errorCampos: 'Ingresa tu email y contraseña',
    crearCuenta: 'Crear cuenta',
    nombreCompleto: 'Tu nombre completo',
    confirmarContrasena: 'Confirmar contraseña',
    contrasenaMinimo: 'La contraseña debe tener mínimo 6 caracteres',
    contrasenasNoCoinciden: 'Las contraseñas no coinciden',
    ingresaNombre: 'Ingresa tu nombre',
    ingresaCorreo: 'Ingresa tu correo',
    cuentaCreada: 'Tu cuenta fue creada correctamente',
    correoEnUso: 'Este correo ya está registrado',
    yaTieneCuenta: '¿Ya tienes cuenta? Inicia sesión',
    bienvenido: '¡Bienvenido!',
    misEventos: 'Mis Eventos',
    sinEventos: 'Aún no tienes eventos',
    creaEvento: 'Crea tu primer evento de regalos',
    eventosDondeParticipo: 'Eventos donde participo',
    sinParticipar: 'No te has unido a ningún evento',
    usaCodigo: 'Usa un código para unirte',
    crearNuevoEvento: '+ Crear nuevo evento',
    unirseConCodigo: '🔑 Unirse con código',
    cerrarSesion: 'Cerrar sesión',
    cerrarSesionPregunta: '¿Estás seguro que quieres salir?',
    salir: 'Salir',
    cancelar: 'Cancelar',
    participante: 'Participante',
    nuevoEvento: '🎉 Nuevo Evento',
    nombreEvento: 'Nombre del evento *',
    descripcion: 'Descripción',
    fecha: 'Fecha',
    ejNombre: 'Ej: Cumpleaños de María',
    ejDescripcion: 'Describe el evento...',
    ejFecha: 'Ej: 25 de diciembre 2025',
    creando: 'Creando...',
    crearEventoBtn: 'Crear evento',
    eventoCreado: '¡Evento creado!',
    codigoCompartir: 'Tu código para compartir es:',
    nombreObligatorio: 'El nombre del evento es obligatorio',
    errorCrear: 'No se pudo crear el evento',
    codigoParaCompartir: 'Código para compartir',
    listaRegalos: 'Lista de Regalos',
    sinRegalos: 'Sin regalos todavía',
    agregaPrimero: 'Agrega el primer regalo a tu lista',
    agregarRegalo: '+ Agregar regalo',
    nuevoRegalo: 'Nuevo Regalo',
    nombreRegalo: 'Nombre del regalo *',
    precio: 'Precio (opcional)',
    linkTienda: 'Link de tienda (opcional)',
    guardarRegalo: 'Guardar regalo',
    regaloAgregado: 'Regalo agregado correctamente',
    errorAgregar: 'No se pudo agregar el regalo',
    nombreRegalObligatorio: 'El nombre del regalo es obligatorio',
    eliminar: 'Eliminar',
    eliminarRegalo: 'Eliminar regalo',
    confirmarEliminar: '¿Eliminar este regalo?',
    noSePuedeEliminar: 'Este regalo ya fue apartado',
    errorEliminar: 'No se pudo eliminar',
    compartir: '📤 Compartir',
    mensajeCompartir: 'Te invito a mi lista de regalos',
    uneteConCodigo: 'Únete con este código:',
    descargaApp: 'Descarga Giftu y usa el código para ver y apartar regalos.',
    regresar: '← Regresar',
    disponible: 'Disponible',
    apartado: 'Apartado',
    unirseEvento: '🎁 Unirse a un evento',
    ingresaCodigo: 'Ingresa el código que te compartieron',
    codigoEvento: 'Código del evento',
    unirseBtn: 'Unirse al evento',
    codigoIncorrecto: 'Código incorrecto, verifica e intenta de nuevo',
    errorUnirse: 'No se pudo unir al evento',
    ingresaCodigoError: 'Ingresa el código del evento',
    misRegalosApartados: '🎁 Mis regalos apartados',
    cancelarApartado: 'Cancelar apartado',
    tuLoApartaste: '✓ Tú lo apartaste',
    noDisponible: 'No disponible',
    disponibleApartar: 'Disponible — toca para apartar',
    apartarRegalo: '¿Apartar regalo?',
    quieresApartar: '¿Quieres apartar este regalo?',
    siApartar: 'Sí, apartar',
    apartadoExito: 'Apartaste el regalo correctamente',
    errorApartar: 'No se pudo apartar el regalo',
    cancelarApartadoPregunta: '¿Cancelar apartado?',
    quieresLiberar: '¿Quieres liberar este regalo?',
    siCancelar: 'Sí, cancelar',
    regaloCancelado: 'El regalo fue liberado',
    errorCancelar: 'No se pudo cancelar',
    listo: '¡Listo!',
    error: 'Error',
    ok: 'OK',
  },
  en: {
    appNombre: '🎁 Giftu',
    iniciaSesion: 'Sign in',
    correo: 'Email address',
    contrasena: 'Password',
    entrar: 'Sign in',
    noTieneCuenta: "Don't have an account? Sign up",
    errorCredenciales: 'Incorrect email or password',
    errorCampos: 'Please enter your email and password',
    crearCuenta: 'Create account',
    nombreCompleto: 'Your full name',
    confirmarContrasena: 'Confirm password',
    contrasenaMinimo: 'Password must be at least 6 characters',
    contrasenasNoCoinciden: 'Passwords do not match',
    ingresaNombre: 'Please enter your name',
    ingresaCorreo: 'Please enter your email',
    cuentaCreada: 'Your account was created successfully',
    correoEnUso: 'This email is already registered',
    yaTieneCuenta: 'Already have an account? Sign in',
    bienvenido: 'Welcome!',
    misEventos: 'My Events',
    sinEventos: "You don't have any events yet",
    creaEvento: 'Create your first gift event',
    eventosDondeParticipo: 'Events I joined',
    sinParticipar: "You haven't joined any events",
    usaCodigo: 'Use a code to join',
    crearNuevoEvento: '+ Create new event',
    unirseConCodigo: '🔑 Join with code',
    cerrarSesion: 'Sign out',
    cerrarSesionPregunta: 'Are you sure you want to sign out?',
    salir: 'Sign out',
    cancelar: 'Cancel',
    participante: 'Participant',
    nuevoEvento: '🎉 New Event',
    nombreEvento: 'Event name *',
    descripcion: 'Description',
    fecha: 'Date',
    ejNombre: "Ex: Maria's Birthday",
    ejDescripcion: 'Describe the event...',
    ejFecha: 'Ex: December 25, 2025',
    creando: 'Creating...',
    crearEventoBtn: 'Create event',
    eventoCreado: 'Event created!',
    codigoCompartir: 'Your sharing code is:',
    nombreObligatorio: 'Event name is required',
    errorCrear: 'Could not create the event',
    codigoParaCompartir: 'Sharing code',
    listaRegalos: 'Gift List',
    sinRegalos: 'No gifts yet',
    agregaPrimero: 'Add the first gift to your list',
    agregarRegalo: '+ Add gift',
    nuevoRegalo: 'New Gift',
    nombreRegalo: 'Gift name *',
    precio: 'Price (optional)',
    linkTienda: 'Store link (optional)',
    guardarRegalo: 'Save gift',
    regaloAgregado: 'Gift added successfully',
    errorAgregar: 'Could not add the gift',
    nombreRegalObligatorio: 'Gift name is required',
    eliminar: 'Delete',
    eliminarRegalo: 'Delete gift',
    confirmarEliminar: 'Delete this gift?',
    noSePuedeEliminar: 'This gift has already been reserved',
    errorEliminar: 'Could not delete',
    compartir: '📤 Share',
    mensajeCompartir: 'I invite you to my gift list',
    uneteConCodigo: 'Join with this code:',
    descargaApp: 'Download Giftu and use the code to view and reserve gifts.',
    regresar: '← Back',
    disponible: 'Available',
    apartado: 'Reserved',
    unirseEvento: '🎁 Join an event',
    ingresaCodigo: 'Enter the code you received',
    codigoEvento: 'Event code',
    unirseBtn: 'Join event',
    codigoIncorrecto: 'Incorrect code, please check and try again',
    errorUnirse: 'Could not join the event',
    ingresaCodigoError: 'Please enter the event code',
    misRegalosApartados: '🎁 My reserved gifts',
    cancelarApartado: 'Cancel reservation',
    tuLoApartaste: '✓ You reserved this',
    noDisponible: 'Not available',
    disponibleApartar: 'Available — tap to reserve',
    apartarRegalo: 'Reserve gift?',
    quieresApartar: 'Do you want to reserve this gift?',
    siApartar: 'Yes, reserve',
    apartadoExito: 'You reserved the gift successfully',
    errorApartar: 'Could not reserve the gift',
    cancelarApartadoPregunta: 'Cancel reservation?',
    quieresLiberar: 'Do you want to release this gift?',
    siCancelar: 'Yes, cancel',
    regaloCancelado: 'The gift was released',
    errorCancelar: 'Could not cancel',
    listo: 'Done!',
    error: 'Error',
    ok: 'OK',
  }
};

type IdiomaContextType = {
  idioma: Idioma;
  t: typeof textos.es;
  cambiarIdioma: (idioma: Idioma) => void;
};

const IdiomaContext = createContext<IdiomaContextType>({
  idioma: 'es',
  t: textos.es,
  cambiarIdioma: () => {},
});

export function IdiomaProvider({ children }: { children: React.ReactNode }) {
  const [idioma, setIdioma] = useState<Idioma>('es');

  useEffect(() => {
    AsyncStorage.getItem('idioma').then((valor) => {
      if (valor === 'es' || valor === 'en') {
        setIdioma(valor);
      }
    });
  }, []);

  const cambiarIdioma = async (nuevoIdioma: Idioma) => {
    setIdioma(nuevoIdioma);
    await AsyncStorage.setItem('idioma', nuevoIdioma);
  };

  return (
    <IdiomaContext.Provider value={{ idioma, t: textos[idioma], cambiarIdioma }}>
      {children}
    </IdiomaContext.Provider>
  );
}

export function useIdioma() {
  return useContext(IdiomaContext);
}